name: Sync to Gitee

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:laomst/ccbar.git
          destination-repo: git@gitee.com:laomst/ccbar.git
